### ISSUE TITLE
Замечания по лаб. 2

### ISSUE THREAD

**Issue by sergey-shambir** [ooccttoobbeerr/lab_2#1]
- в названиях `pole`, `nolik`, `krest`, `bot` наблюдается транслит, которого быть не должно
- названия `int s = 0, r = 0, n = 0;` слишком короткие, из одной буквы не понятна цель переменной
- вот это вынести в отдельную функцию:

``` cpp
for (y = 0; y < 3; y++){
    for (x = 0; x < 3; x++){
        if (pole[y][x] == krest){
            s++;
        }
    }
}
```
- вот такие конструкции можно везде вынести в функцию, принимающую пары индексов в аргументах:

``` cpp
else if (pole[2][1] == krest && pole[1][2] == krest && pole[2][2] == 0){
    pole[2][2] = nolik;
}
```
- функция main слишком велика, она не должна выполнять так много разных задач. Следует выделить подзадачи в функции.

**Comment by ooccttoobbeerr** [comment]
Исправила

**Comment by sergey-shambir** [comment]
Принято
